name: Update gist
on:
  repository_dispatch:
    types: [build-event]
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Update gist
        uses: maxam2017/productive-box@master
        env:
          GH_TOKEN: ${{ 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 }}
          GIST_ID: https://gist.github.com/eunseo0105
          TIMEZONE: Asia/Taipei
